ipAddr: 127.0.0.1
server:
  port: 6000
spring:
  application:
    name: gulimall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos

    gateway:
      routes:
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path: /api/product/**
          filters:
            - RewritePath:/api/(?<segment>.*),/$\{segment}
        - id: file_upload_route
          uri: lb://gulimall-file
          predicates:
            - Path: /api/thirdparty/**
          filters:
            - RewritePath:/api/thirdparty/(?<segment>.*),/$\{segment}

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0